---
- name: import 2nd repo role
  hosts: localhost
  gather_facts: false
  roles:
    - abc
  tags: first-test


- name: import 2nd repo role
  hosts: localhost
  gather_facts: false
  tasks:
    - name: import role tetsing one
      import_role:
        name: testing-role
  tags: second-test
